# syntax=docker/dockerfile:1.6

FROM golang:1.23 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o worker ./cmd/worker

FROM gcr.io/distroless/base-debian12
WORKDIR /srv
COPY --from=builder /app/worker /srv/worker

ENTRYPOINT ["/srv/worker"]

