targets:
  $default:
    builders:
      freezed:
        options:
          union_value_case: pascal
      json_serializable:
        options:
          explicit_to_json: true
      retrofit_generator:
        options:
          auto_generate_impl: true

