package db

import (
	"context"
	"database/sql"
	"fmt"
)

// Store defines the interfaces generated by sqlc. It is satisfied by *Queries.
type Store interface {
	Querier
}

// Wrap constructs a sqlc store around the provided database connection.
func Wrap(db *sql.DB) *Queries {
	return New(db)
}

// WithTx executes fn within a database transaction.
func WithTx(ctx context.Context, db *sql.DB, fn func(*sql.Tx) error) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}

	if err := fn(tx); err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("rollback: %v (original err: %w)", rbErr, err)
		}
		return err
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", err)
	}

	return nil
}

