package db

// Code generated by sqlc placeholder. DO NOT EDIT.

import (
    "context"
    "database/sql"
)

// DBTX represents the subset of database/sql methods sqlc relies on.
type DBTX interface {
    ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
    QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
    QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// Queries is a stub struct until sqlc generates the actual implementation.
type Queries struct {
    db DBTX
}

// New returns a new Queries stub.
func New(db DBTX) *Queries {
    return &Queries{db: db}
}

// Querier is implemented by sqlc generated Queries.
type Querier interface {
    CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
    GetUserByEmail(ctx context.Context, email string) (User, error)
    GetUserByID(ctx context.Context, id string) (User, error)
}

// CreateUserParams placeholder struct.
type CreateUserParams struct {
    Handle      string
    Email       string
    DisplayName string
    IsAnon      bool
    Plan        string
}

// User placeholder struct.
type User struct {
    ID          string
    Handle      string
    Email       string
    DisplayName string
    IsAnon      bool
    Plan        string
}

